services:
  agroai-api-app:
    container_name: agroai_api_container
    build: . 
    restart: always
    ports:
      - "8000:8000" 
    command: gunicorn -w 16 App.Main:app --bind 0.0.0.0:8000 --timeout 300
    env_file:
      - Config/.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
      - pgadmin

  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      ports:
        - "5050:80"
      env_file:
        - ./Config/.env

      depends_on:
        - postgres

  postgres:
    container_name: postgres_container
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - Config/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  
volumes:
  postgres_db: