CREATE DATABASE "AgroAI_API";

\c "AgroAI_API"


CREATE TABLE roles
(
    role_id bigint generated by default as identity,
    role_type character varying not null,

    constraint roles_pkey primary key (role_id)
);

INSERT INTO roles
    (role_id, role_type) 
VALUES 
    (1, 
    'super admin'),

    (2, 
    'admin'),

    (3, 
    'employee') 
;


CREATE TABLE users
(
    user_id uuid not null default gen_random_uuid (),
    email character varying not null,
    first_name character varying not null,
    last_name character varying not null,
    password character varying not null,
    role bigint not null,
    working_status boolean not null,
    created_at timestamp with time zone not null default now(),

    constraint users_pkey1 primary key (email),
    constraint users_user_id_key unique (user_id),
    constraint public_users_role_fkey foreign key (role) references roles (role_id)
);

INSERT INTO users
    (email, first_name, last_name, password, role, working_status) 
VALUES 
    ('lingges@cerdas.com.my', 
    'lingges',
    'arulsamy', 
    'f5ef1f7b17ea75fe529e9cdea3e3a5d97f6b697c1b3fc59453eba32b40fab25f',
    1,
    TRUE),
    
    ('ali@cerdas.com.my', 
    'ali',
    'abdaal', 
    '56ba118c02f0a55a065d71a7ada5e9c0d4d664f447d092a9a4fab9223b3e3019',
    2,
    TRUE),

    ('cheong@cerdas.com.my', 
    'cheong',
    'yong', 
    '93e77f994efa0af31a5c4e5053aa025a58ffc787db74f44fbd2726118e2fae8f',
    3,
    TRUE)
;



